### PR TITLE
Add percent unit into LUA

### PR DESCRIPTION
**Pull request by lichtl**
Based on the OpenTX documents there had been a change on the unit values. Added a new variable and a note.

### CODE REVIEW

**Comment by DynamikArray** [comment]
I'm getting the same issue with your code that i original had with mine, this does not play the  "Percentage" clip, but plays the "Feet" clip, on my radio at least.   

What was happening on your radio, that made you change it?  I will see if that behavior is happening with other users?

**Comment by DynamikArray** [comment]
I do think that the variable i used in the function call to playNumber() should be changed to a local like you set up though,

**Comment by lichtl** [comment]
Ok. But maybe good to add a note there since I initially thought I had a problem with my language pack since all values have been reported as "Miles per Hour"

Original Script was reporting "Miles per hour" on my Taranis Plus running 2.1.8

Maybe your soundpack is outdates (since there was some changes in 2.1)

I'm using a soundpack generated through https://docs.google.com/spreadsheets/d/1rmxA-3u7dH5ROFidpWJYp3Yl_lnSBQdMyaUviQAxYzo/edit#gid=226584730

But I can also confirm that the downloaded soundpack (en) from the OpenTX page had the same issue

**Comment by DynamikArray** [comment]
Ooooh, language pack issues?   What language pack are you using, because if i follow the link you sent to documentation, the value of "8" is the percentage value, and its suppose to play wav file 130 which plays percentage.

Using your submitted change of 13 would do exactly what it is doing for me and saying feet, so for now, it does appear that your radio is incorrect.

Does that make sense?

**Comment by DynamikArray** [comment]
SMH- I neglected the firmware differences, i think my systems files are mixed up.

**Comment by DynamikArray** [comment]
I'll add a version check 
https://opentx.gitbooks.io/opentx-lua-reference-guide/content/general/getVersion.html
and update the local sound constant variable to use the correct value based off that.

Thanks for the help pointing that one out.

**Comment by lichtl** [comment]
Ok. Adding a version check should sort it out as well. Closing the PR

**Comment by DynamikArray** [comment]
My sound pack is incorrect, the code you submitted is good, and should be used.  I'll make an updated note in the wiki, about sound issues and ensuring the system sounds are up to date.  I'm surprised nobody else mentioned since this issue.

**Pull request merged**
